name: Changelog
on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Version Changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          git-message: "chore(release): {version}"
          git-user-name: "Krish Gupta"
          git-user-email: "krshkodes@gmail.com"
          preset: "angular"

      - name: GitHub Releases
        uses: actions/create-release@v1
        if: ${{ steps.release.outputs.skipped == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.release.outputs.version }}
          release_name: ${{ steps.release.outputs.tag }}
          body: ${{ steps.release.outputs.clean_changelog }}
